Repository MJU-InsuranceSystem/Insurance-System-BE, pull requests merged in 2024-11, with the labels that each got.

#6 Feat : 엔티티 세팅
  src/main/java/fourservings_fiveservings/insurance_system_be/insurance/apply/InsuranceApplication.java
  src/main/java/fourservings_fiveservings/insurance_system_be/insurance/apply/InsuranceApplyListImpl.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/contract/Contract.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/contract/ContractListImpl.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/contract/ContractManagementTeamMethod.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/RewardSupportTeamMethod.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/model/Accident.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/model/AccidentListImpl.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/model/ClaimInsurance.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/underwrite/UnderwriteTeamMethod.java
  src/main/java/fourservings_fiveservings/insurance_system_be/user/customer/CustomerProcessManager.java
  src/main/java/fourservings_fiveservings/insurance_system_be/user/worker/Worker.java
  src/main/resources/application-prod.yml
Labels: ⚙️ 세팅

#12 Fix : yml 설정 오류 수정
  src/main/resources/application.yml
Labels: fix

#13 Refactor : auth 커스텀 Exception 처리
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/controller/AuthController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/custom/CustomUserDetails.java
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/service/AuthService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/constant/ResultType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/exception/BusinessException.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/exception/constant/ErrorType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/response/constant/ResultType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/response/constant/SuccessType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/response/vo/ApiResponse.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/vo/ApiResponse.java
  src/main/java/fourservings_fiveservings/insurance_system_be/domain/user/controller/UserController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/domain/user/service/UserService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/api/ProductApi.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/controller/ProductController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/entity/ApproveStatus.java
Labels: ⚙️ 세팅, 🛠️ 리팩토링

#23 refactor : 줄 맞춤
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/custom/CustomUserDetails.java
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/jwt/service/JwtService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/api/ProductApi.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/controller/ProductController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/controller/dto/DesignProductRequestDto.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/dto/DesignProductRequestDto.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/entity/Product.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/repository/ProductRepository.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/service/ProductService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/product/service/componet/ProductManager.java
Labels: 🛠️ 리팩토링

#30 fix : 컴파일 에러 수정
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/entity/Accident.java
Labels: fix

#38 Feat : 보험 납부금 조회, 고객 사건 접수하기 구현
  src/main/java/fourservings_fiveservings/insurance_system_be/auth/custom/CustomUserDetails.java
  src/main/java/fourservings_fiveservings/insurance_system_be/common/exception/constant/ErrorType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/contract/entity/common/type/PaymentMethod.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/contract/service/implement/ContractFinder.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/api/PaymentApi.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/controller/PaymentController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/controller/dto/request/PayRequestDto.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/controller/dto/response/PaymentListResponse.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/entity/Payment.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/repository/PaymentRepository.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/payment/service/PaymentService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/plan/service/InsurancePlanService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/api/AccidentApi.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/controller/AccidentController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/controller/AccidentCustomerController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/controller/AccidentWorkerController.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/controller/dto/request/RegisterAccidentRequestDto.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/entity/Accident.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/entity/enums/AccidentType.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/repository/AccidentRepository.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/rewardSupport/accident/service/AccidentService.java
  src/main/java/fourservings_fiveservings/insurance_system_be/team/sale/entity/BusinessActivity.java
  src/main/java/fourservings_fiveservings/insurance_system_be/user/controller/dto/request/SetAccountRequestDto.java
  src/main/java/fourservings_fiveservings/insurance_system_be/user/entity/Customer.java
  src/main/java/fourservings_fiveservings/insurance_system_be/user/entity/embeded/Account.java
Labels: 🌟 기능
